/**
* Test class of HorseWS class
* @Author : Nikhil Jaitly
* @Created Date : 24/06/2016
*/



@isTest
private class HorseWSTest {
	
	@isTest static void testSCHorseAnyID() {
		new HorseWS.SCHorseAnyID();
	}
	
	@isTest static void testupgradeHorsePassportResponse_element() {
		new HorseWS.upgradeHorsePassportResponse_element();
	}

	@isTest static void testsearchForHorseAlt_element() {
		new HorseWS.searchForHorseAlt_element();
	}

	@isTest static void testHorseOwner_element() {
		new HorseWS.assignHorseOwner_element();
	}

	@isTest static void testHorseOwner() {
		new HorseWS.HorseOwner();
	}

	@isTest static void testconfirmAddHorseResponse_element() {
		new HorseWS.confirmAddHorseResponse_element();
	}

	@isTest static void testchangeHorseNameResponse_element() {
		new HorseWS.changeHorseNameResponse_element();
	}

	@isTest static void testArrayOfStudBook() {
		new HorseWS.ArrayOfStudBook();
	}

	@isTest static void testgetHorse_element() {
		new HorseWS.getHorse_element();
	}

	@isTest static void testuploadHorseDocumentResponse_element() {
		new HorseWS.uploadHorseDocumentResponse_element();
	}

	@isTest static void testSCHorseRegistration() {
		new HorseWS.SCHorseRegistration();
	}	
	
	@isTest static void testaddHorseResponse_element() {
		new HorseWS.addHorseResponse_element();
	}	
	
	@isTest static void testconfirmUpdateHorse_element() {
		new HorseWS.confirmUpdateHorse_element();
	}	
	
	@isTest static void testgetHorseRegistrationYearListResponse_element() {
		new HorseWS.getHorseRegistrationYearListResponse_element();
	}	
	
	@isTest static void testSearchClassesHelper_element() {
		new HorseWS.SearchClassesHelper_element();
	}	
	
	@isTest static void testgetHorseOwnerResponse_element() {
		new HorseWS.getHorseOwnerResponse_element();
	}	
	
	@isTest static void testaddTrainerToHorse_element() {
		new HorseWS.addTrainerToHorse_element();
	}	
	
	@isTest static void testdownloadHorseStickerResponse_element() {
		new HorseWS.downloadHorseStickerResponse_element();
	}	
	
	@isTest static void testSCHorseName() {
		new HorseWS.SCHorseName();
	}	
	
	@isTest static void testSCHorseRegDateTo() {
		new HorseWS.SCHorseRegDateTo();
	}	
	
	@isTest static void testgetHorseResponse_element() {
		new HorseWS.getHorseResponse_element();
	}	
	
	@isTest static void testupgradeHorseRecognitionCard_element() {
		new HorseWS.upgradeHorseRecognitionCard_element();
	}	
	
	@isTest static void testconfirmUpdateHorseResponse_element() {
		new HorseWS.confirmUpdateHorseResponse_element();
	}	
	
	@isTest static void testSCBase() {
		new HorseWS.SCBase();
	}	
	
	@isTest static void testupdateHorseNoviceQualification_element() {
		new HorseWS.updateHorseNoviceQualification_element();
	}	
	
	@isTest static void testSCHorseCurrentOwner() {
		new HorseWS.SCHorseCurrentOwner();
	}	
	
	@isTest static void testupdateHorse_element() {
		new HorseWS.updateHorse_element();
	}	
	
	@isTest static void testdeleteHorseNoviceQualification_element() {
		new HorseWS.deleteHorseNoviceQualification_element();
	}	
	
	@isTest static void testdeleteHorseNoviceQualificationResponse_element() {
		new HorseWS.deleteHorseNoviceQualificationResponse_element();
	}	
	
	@isTest static void testHorseTrainer() {
		new HorseWS.HorseTrainer();
	}	
	
	@isTest static void testArrayOfSCBase() {
		new HorseWS.ArrayOfSCBase();
	}	
	
	@isTest static void testgetHorseRegistrationList_element() {
		new HorseWS.getHorseRegistrationList_element();
	}	
	
	@isTest static void testsearchHorseTrainers_element() {
		new HorseWS.searchHorseTrainers_element();
	}	
	
	@isTest static void testStudBook() {
		new HorseWS.StudBook();
	}	
	
	@isTest static void testBaseEntityFacadeOfENDURANCE_NATIONAL_RESULT() {
		new HorseWS.BaseEntityFacadeOfENDURANCE_NATIONAL_RESULT();
	}	
	
	@isTest static void testgetAdminChangeReasonListResponse_element() {
		new HorseWS.getAdminChangeReasonListResponse_element();
	}	
	
	@isTest static void testHorseRegistration() {
		new HorseWS.HorseRegistration();
	}	
	
	@isTest static void testArrayOfEnduranceNationalResult() {
		new HorseWS.ArrayOfEnduranceNationalResult();
	}	
	
	@isTest static void testconfirmAddHorse_element() {
		new HorseWS.confirmAddHorse_element();
	}	
	
	@isTest static void testgetStudBookList_element() {
		new HorseWS.getStudBookList_element();
	}	
	
	@isTest static void testconfirmChangeHorseNameResponse_element() {
		new HorseWS.confirmChangeHorseNameResponse_element();
	}	
	
	@isTest static void testdownloadHorseDiagramResponse_element() {
		new HorseWS.downloadHorseDiagramResponse_element();
	}	
	
	@isTest static void testsearchForHorseAltResponse_element() {
		new HorseWS.searchForHorseAltResponse_element();
	}	
	
	@isTest static void testgetHorseCurrentNoviceQualificationResponse_element() {
		new HorseWS.getHorseCurrentNoviceQualificationResponse_element();
	}	
	
	@isTest static void testconfirmChangeHorseName_element() {
		new HorseWS.confirmChangeHorseName_element();
	}	
	
	@isTest static void testsearchForHorseResponse_element() {
		new HorseWS.searchForHorseResponse_element();
	}	
	
	@isTest static void testchangeHorseName_element() {
		new HorseWS.changeHorseName_element();
	}	
	
	@isTest static void testgetAdminChangeReasonList_element() {
		new HorseWS.getAdminChangeReasonList_element();
	}	
	
	@isTest static void testgetStudBookListResponse_element() {
		new HorseWS.getStudBookListResponse_element();
	}	
	
	@isTest static void testArrayOfHorseDuplicate() {
		new HorseWS.ArrayOfHorseDuplicate();
	}	
	
	@isTest static void testAuthHeader() {
		new HorseWS.AuthHeader();
	}


	@isTest static void testgetHorses_element() {
		new HorseWS.getHorses_element();
	}


	@isTest static void testuploadHorseDocument_element() {
		new HorseWS.uploadHorseDocument_element();
	}


	@isTest static void testSCHorseRegDateFrom() {
		new HorseWS.SCHorseRegDateFrom();
	}


	@isTest static void testgetHorseNameHistoryListResponse_element() {
		new HorseWS.getHorseNameHistoryListResponse_element();
	}


	@isTest static void testArrayOfHorseColor() {
		new HorseWS.ArrayOfHorseColor();
	}


	@isTest static void testSearchCriteria() {
		new HorseWS.SearchCriteria();
	}


	@isTest static void testgetHorseRegistrationYearList_element() {
		new HorseWS.getHorseRegistrationYearList_element();
	}


	@isTest static void testuploadHorseDiagram_element() {
		new HorseWS.uploadHorseDiagram_element();
	}


	@isTest static void testSCHorseInclHistNames() {
		new HorseWS.SCHorseInclHistNames();
	}


	@isTest static void testsearchHorseTrainersResponse_element() {
		new HorseWS.searchHorseTrainersResponse_element();
	}


	@isTest static void testArrayOfHorse() {
		new HorseWS.ArrayOfHorse();
	}


	@isTest static void testSearchClassesHelperResponse_element() {
		new HorseWS.SearchClassesHelperResponse_element();
	}


	@isTest static void testgetAdminChangeStatusListResponse_element() {
		new HorseWS.getAdminChangeStatusListResponse_element();
	}


	@isTest static void testregisterHorse_element() {
		new HorseWS.registerHorse_element();
	}


	@isTest static void testupdateHorseNoviceQualificationResponse_element() {
		new HorseWS.updateHorseNoviceQualificationResponse_element();
	}


	@isTest static void testupgradeHorseRecognitionCardResponse_element() {
		new HorseWS.upgradeHorseRecognitionCardResponse_element();
	}


	@isTest static void testgetHorseColorList_element() {
		new HorseWS.getHorseColorList_element();
	}


	@isTest static void testuploadHorseDiagramResponse_element() {
		new HorseWS.uploadHorseDiagramResponse_element();
	}


	@isTest static void testSCHorseRegDiscipline() {
		new HorseWS.SCHorseRegDiscipline();
	}


	@isTest static void testHorse() {
		new HorseWS.Horse();
	}


	@isTest static void testHorseNew() {
		new HorseWS.HorseNew();
	}


	@isTest static void testgetHorseRegistrationListResponse_element() {
		new HorseWS.getHorseRegistrationListResponse_element();
	}


	@isTest static void testaddHorseNoviceQualificationResponse_element() {
		new HorseWS.addHorseNoviceQualificationResponse_element();
	}


	@isTest static void testupgradeHorsePassport_element() {
		new HorseWS.upgradeHorsePassport_element();
	}


	@isTest static void testdownloadHorseDiagram_element() {
		new HorseWS.downloadHorseDiagram_element();
	}


	@isTest static void testAdminChangeReasonHorse() {
		new HorseWS.AdminChangeReasonHorse();
	}


	@isTest static void testgetHorseNameHistoryList_element() {
		new HorseWS.getHorseNameHistoryList_element();
	}


	@isTest static void testArrayOfAdminChangeReasonHorse() {
		new HorseWS.ArrayOfAdminChangeReasonHorse();
	}


	@isTest static void testaddHorseNoviceQualification_element() {
		new HorseWS.addHorseNoviceQualification_element();
	}


	@isTest static void testEnduranceNationalResult() {
		new HorseWS.EnduranceNationalResult();
	}


	@isTest static void testrequestAdministrationChange_element() {
		new HorseWS.requestAdministrationChange_element();
	}


	@isTest static void testSCHorseStudbook() {
		new HorseWS.SCHorseStudbook();
	}


	@isTest static void testArrayOfHorseTrainer() {
		new HorseWS.ArrayOfHorseTrainer();
	}


	@isTest static void testArrayOfHorseRegistration() {
		new HorseWS.ArrayOfHorseRegistration();
	}


	@isTest static void testgetHorsesResponse_element() {
		new HorseWS.getHorsesResponse_element();
	}


	@isTest static void testSCHorsePony() {
		new HorseWS.SCHorsePony();
	}


	@isTest static void testHorseName() {
		new HorseWS.HorseName();
	}


	@isTest static void testArrayOfAdminChangeStatusHorse() {
		new HorseWS.ArrayOfAdminChangeStatusHorse();
	}


	@isTest static void testArrayOfHorseName() {
		new HorseWS.ArrayOfHorseName();
	}


	@isTest static void testgetAdminChangeStatusList_element() {
		new HorseWS.getAdminChangeStatusList_element();
	}


	@isTest static void testaddHorse_element() {
		new HorseWS.addHorse_element();
	}


	@isTest static void testMessage() {
		new HorseWS.Message();
	}


	@isTest static void testArrayOfSearchCriteria() {
		new HorseWS.ArrayOfSearchCriteria();
	}


	@isTest static void testSearchClasses() {
		new HorseWS.SearchClasses();
	}


	@isTest static void testupdateHorseResponse_element() {
		new HorseWS.updateHorseResponse_element();
	}


	@isTest static void testgetHorseColorListResponse_element() {
		new HorseWS.getHorseColorListResponse_element();
	}


	@isTest static void testHorseDuplicate() {
		new HorseWS.HorseDuplicate();
	}


	@isTest static void testrequestAdministrationChangeResponse_element() {
		new HorseWS.requestAdministrationChangeResponse_element();
	}

	
	@isTest static void testHorseColor() {
		new HorseWS.HorseColor();
	}

	@isTest static void testsearchForHorse_element() {
		new HorseWS.searchForHorse_element();
	}


	@isTest static void testgetHorseCurrentNoviceQualification_element() {
		new HorseWS.getHorseCurrentNoviceQualification_element();
	}


	@isTest static void testdownloadHorseSticker_element() {
		new HorseWS.downloadHorseSticker_element();
	}


	@isTest static void testAdminChangeStatusHorse() {
		new HorseWS.AdminChangeStatusHorse();
	}


	@isTest static void testArrayOfMessage() {
		new HorseWS.ArrayOfMessage();
	}


	@isTest static void testSCHorseHorseStatus() {
		new HorseWS.SCHorseHorseStatus();
	}


	@isTest static void testregisterHorseResponse_element() {
		new HorseWS.registerHorseResponse_element();
	}


	@isTest static void testgetHorseOwner_element() {
		new HorseWS.getHorseOwner_element();
	}


	@isTest static void testArrayOfString() {
		new HorseWS.ArrayOfString();
	}


	@isTest static void testValidatableEntityFacadeOfENDURANCE_NATIONAL_RESULT() {
		new HorseWS.ValidatableEntityFacadeOfENDURANCE_NATIONAL_RESULT();
	}


	@isTest static void testaddTrainerToHorseResponse_element() {
		new HorseWS.addTrainerToHorseResponse_element();
	}


	@isTest static void testSCHorseAdminNF() {
		new HorseWS.SCHorseAdminNF();
	}


	@isTest static void testassignHorseOwnerResponse_element() {
		new HorseWS.assignHorseOwnerResponse_element();
	}


	@isTest static void testSCHorsePendAdmNFReq() {
		new HorseWS.SCHorsePendAdmNFReq();
	}

	@isTest static void testHorseWSSoap() {


		Test.setMock(WebServiceMock.class, new HorseWSMock());
		Test.startTest();	
		HorseWS.HorseWSSoap hsp = new HorseWS.HOrseWSSoap();

		hsp.getHorses(new HorseWS.ArrayOfString());
		hsp.downloadHorseSticker('','');
        hsp.requestAdministrationChange('');
		hsp.searchForHorseAlt(new HorseWS.ArrayOfSearchCriteria());
		hsp.assignHorseOwner('',new HorseWS.HorseOwner());
		hsp.upgradeHorseRecognitionCard('');
		hsp.getHorseNameHistoryList('');
		hsp.updateHorse(new HorseWS.Horse());
       // hsp.SearchClassesHelper(new HorseWS.SearchClasses());
       	hsp.searchForHorse(new HorseWS.ArrayOfSCBase());
        hsp.registerHorse('',2016 ,new HorseWS.ArrayOfString());
        hsp.uploadHorseDocument('','','','','');
       // hsp.getAdminChangeStatusList();
        hsp.downloadHorseDiagram('');
        hsp.getHorseOwner('');
        hsp.addTrainerToHorse('',564,System.now(),System.now());
       // hsp.getStudBookList();
        hsp.searchHorseTrainers('',56,System.now(),56);
        hsp.getHorse('');
        hsp.addHorse(new HorseWS.HorseNew());
        hsp.getHorseRegistrationYearList('',678);
      //  hsp.getHorseColorList();
        hsp.confirmUpdateHorse('');
        hsp.changeHorseName(new HorseWS.HorseName());
		hsp.confirmChangeHorseName('');
       // hsp.getAdminChangeReasonList();
        hsp.upgradeHorsePassport('');
        hsp.getHorseCurrentNoviceQualification('');
        hsp.deleteHorseNoviceQualification('',System.now());
        hsp.confirmAddHorse('');
        hsp.addHorseNoviceQualification('',new HorseWS.ArrayOfEnduranceNationalResult());
        hsp.getHorseRegistrationList('');
        hsp.uploadHorseDiagram('','','');
        hsp.updateHorseNoviceQualification('',System.now(),new HorseWS.ArrayOfEnduranceNationalResult());
        Test.stopTest();
	}


	
	/*private class WebServiceMockImpl implements WebServiceMock
    {
        public void doInvoke(
            Object stub, Object request, Map<String, Object> response,
            String endpoint, String soapAction, String requestName,
            String responseNS, String responseName, String responseType)
        {
            if(request instanceof HorseWS.getHorses_element request_x)
                response.put('response_x', new HorseWS.getHorses_element request_x());
            return;
        }
    }


	*/
	

}