/**
* Test class of ResultWS class
* @Author : Nikhil Jaitly
* @Created Date : 26/06/2016
*/



@isTest
private class ResultWSTest {
	
	@isTest static void testgetCompetition_element() {
		new ResultWS.getCompetition_element();
	}
	
	@isTest static void testCompetition() {
		new ResultWS.Competition();
	}


	@isTest static void testHorseQualification() {
		new ResultWS.HorseQualification();
	}
	

	@isTest static void testgetCompetitions_element() {
		new ResultWS.getCompetitions_element();
	}
	

	@isTest static void testNFResultCommon() {
		new ResultWS.NFResultCommon();
	}
	

	@isTest static void testArrayOfNFResult() {
		new ResultWS.ArrayOfNFResult();
	}
	

	@isTest static void testNFResultJumping() {
		new ResultWS.NFResultJumping();
	}
	

	@isTest static void testNFResultParaDressage() {
		new ResultWS.NFResultParaDressage();
	}
	

	@isTest static void testCombination() {
		new ResultWS.Combination();
	}
	

	@isTest static void testArrayOfCombinationQualification() {
		new ResultWS.ArrayOfCombinationQualification();
	}
	

	@isTest static void testgetNFResults_element() {
		new ResultWS.getNFResults_element();
	}
	

	@isTest static void testgetCompetitionResponse_element() {
		new ResultWS.getCompetitionResponse_element();
	}
	

	@isTest static void testAthleteQualification() {
		new ResultWS.AthleteQualification();
	}
	

	@isTest static void testgetCompetitionsByShowCode_element() {
		new ResultWS.getCompetitionsByShowCode_element();
	}
	

	@isTest static void testCheckHorseEventingQualifications_element() {
		new ResultWS.CheckHorseEventingQualifications_element();
	}
	
	@isTest static void testArrayOfHorseQualification() {
		new ResultWS.ArrayOfHorseQualification();
	}
	

	@isTest static void testsubmitEventResultsResponse_element() {
		new ResultWS.submitEventResultsResponse_element();
	}
	

	@isTest static void testNFResultVaulting() {
		new ResultWS.NFResultVaulting();
	}
	

	@isTest static void testgetCompetitionsByEventCodeResponse_element() {
		new ResultWS.getCompetitionsByEventCodeResponse_element();
	}
	

	@isTest static void testgetCompetitionsByShowCodeResponse_element() {
		new ResultWS.getCompetitionsByShowCodeResponse_element();
	}
	

	@isTest static void testArrayOfCombination() {
		new ResultWS.ArrayOfCombination();
	}
	

	@isTest static void testgetEventResults_element() {
		new ResultWS.getEventResults_element();
	}
	

	@isTest static void testNFResult() {
		new ResultWS.NFResult();
	}
	

	@isTest static void testShow() {
		new ResultWS.Show();
	}
	

	@isTest static void testNFResultReining() {
		new ResultWS.NFResultReining();
	}
	

	@isTest static void testuploadEventResults_element() {
		new ResultWS.uploadEventResults_element();
	}
	

	@isTest static void testMessage() {
		new ResultWS.Message();
	}
	

	@isTest static void testgetCompetitionResultsResponse_element() {
		new ResultWS.getCompetitionResultsResponse_element();
	}
	

	@isTest static void testgetCompetitionsByEventCode_element() {
		new ResultWS.getCompetitionsByEventCode_element();
	}
	

	@isTest static void testNFResultDressage() {
		new ResultWS.NFResultDressage();
	}
	

	@isTest static void testsaveEventResultsResponse_element() {
		new ResultWS.saveEventResultsResponse_element();
	}
	
	@isTest static void testgetCompetitionResults_element() {
		new ResultWS.getCompetitionResults_element();
	}
	

	@isTest static void testCheckCombinationEventingQualifications_element() {
		new ResultWS.CheckCombinationEventingQualifications_element();
	}
	

	@isTest static void testCheckAthleteEventingQualifications_element() {
		new ResultWS.CheckAthleteEventingQualifications_element();
	}
	

	@isTest static void testArrayOfAthleteQualification() {
		new ResultWS.ArrayOfAthleteQualification();
	}
	

	@isTest static void testdownloadEventResultsResponse_element() {
		new ResultWS.downloadEventResultsResponse_element();
	}
	

	@isTest static void testgetCompetitionsResponse_element() {
		new ResultWS.getCompetitionsResponse_element();
	}
	

	@isTest static void testsubmitEventResults_element() {
		new ResultWS.submitEventResults_element();
	}
	

	@isTest static void testsaveEventResults_element() {
		new ResultWS.saveEventResults_element();
	}
	

	@isTest static void testCheckCombinationEventingQualificationsResponse_element() {
		new ResultWS.CheckCombinationEventingQualificationsResponse_element();
	}
	
	@isTest static void testdownloadEventResults_element() {
		new ResultWS.downloadEventResults_element();
	}
	
	
	@isTest static void testArrayOfCompetition() {
		new ResultWS.ArrayOfCompetition();
	}
	

	@isTest static void testBaseQualification() {
		new ResultWS.BaseQualification();
	}
	

	@isTest static void testAuthHeader() {
		new ResultWS.AuthHeader();
	}
	

	@isTest static void testNFResultDriving() {
		new ResultWS.NFResultDriving();
	}
	

	@isTest static void testuploadEventResultsResponse_element() {
		new ResultWS.uploadEventResultsResponse_element();
	}
	

	@isTest static void testArrayOfMessage() {
		new ResultWS.ArrayOfMessage();
	}
	

	@isTest static void testNFResultEndurance() {
		new ResultWS.NFResultEndurance();
	}
	

	@isTest static void testgetEventResultsResponse_element() {
		new ResultWS.getEventResultsResponse_element();
	}
	

	@isTest static void testgetNFResultsResponse_element() {
		new ResultWS.getNFResultsResponse_element();
	}
	

	@isTest static void testNFResultEventing() {
		new ResultWS.NFResultEventing();
	}
	

	@isTest static void testCheckHorseEventingQualificationsResponse_element() {
		new ResultWS.CheckHorseEventingQualificationsResponse_element();
	}
	

	@isTest static void testArrayOfString() {
		new ResultWS.ArrayOfString();
	}
	

	@isTest static void testEvent() {
		new ResultWS.Event();
	}
	

	@isTest static void testArrayOfInt() {
		new ResultWS.ArrayOfInt();
	}
	

	@isTest static void testCheckAthleteEventingQualificationsResponse_element() {
		new ResultWS.CheckAthleteEventingQualificationsResponse_element();
	}
	

	@isTest static void testCombinationQualification() {
		new ResultWS.CombinationQualification();
	}
	
	
	@isTest static void testResultWSSoap() {


		Test.setMock(WebServiceMock.class, new ResultWSMock());
		Test.startTest();	
		ResultWS.ResultWSSoap rsp = new ResultWS.ResultWSSoap();

		rsp.getCompetitionsByEventCode('');
		//rsp.submitEventResults(''));
		rsp.getCompetitions(new ResultWS.ArrayOfString());
		rsp.CheckCombinationEventingQualifications('',new ResultWS.ArrayOfCombination());
		rsp.downloadEventResults('');
		rsp.uploadEventResults('');
		rsp.getNFResults('','','','',System.now(),System.now());
		rsp.getCompetition('');
		rsp.getCompetitionsByShowCode('');
		rsp.getCompetitionResults('');
		rsp.saveEventResults(5);
		rsp.CheckHorseEventingQualifications('',new ResultWS.ArrayOfString());
		rsp.CheckAthleteEventingQualifications('',new ResultWS.ArrayOfInt());
		rsp.getEventResults('');
		Test.stopTest();
	
	}


}